version: 0.0
os: linux

files:
  - source: build/libs/
    destination: /opt/app

hooks:
  AfterInstall:
    - location: deploy-scripts/start.sh
      timeout: 120
  ApplicationStop:
    - location: deploy-scripts/stop.sh
      timeout: 60

