version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  AfterInstall:
    - location: deploy-scripts/start.sh
      timeout: 120
      runas: ubuntu
  ApplicationStop:
    - location: deploy-scripts/stop.sh
      timeout: 60
      runas: ec2-user
