version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - chmod +x gradlew

  build:
    commands:
      - echo "Build Spring Boot executable jar"
      - ./gradlew clean bootJar -x test
      - ls -al build/libs   # ← 이 줄이 핵심 (확인용)

artifacts:
  files:
    - appspec.yml
    - deploy-scripts/start.sh
    - deploy-scripts/stop.sh
    - build/libs/*.jar
